#
# trans-tool
# The translation files checker and syncing tool.
#
# Copyright ©2021-2024 Marcin Orlowski <MarcinOrlowski.com>
# https://github.com/MarcinOrlowski/trans-tool/
#

name: "Unit tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, dev ]

jobs:
  unittests:
    name: "Testing"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        # quotes are needed it is treated as a number and zero at decimal part is gone at runtime
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: "Checkout sources"
        uses: actions/checkout@v4

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: "Look for changed files..."
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            srcs:
              - '**/*.py'

      - name: "Setup Python"
        if: steps.filter.outputs.srcs == 'true'
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}

      - name: "Installing dependencies..."
        if: steps.filter.outputs.srcs == 'true'
        run: pip install -r requirements-dev.txt

      - name: "Running unit tests..."
        if: steps.filter.outputs.srcs == 'true'
        run: python -m unittest discover tests
